# Generated by Django 5.0 on 2024-01-02 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='organisationPaymentQR',
        ),
        migrations.CreateModel(
            name='OrganisationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisationName', models.CharField(max_length=255)),
                ('organisationFocus', models.TextField()),
                ('organisationShortDescription', models.TextField()),
                ('organisationLongDescription', models.TextField()),
                ('organisationImage1', models.ImageField(blank=True, null=True, upload_to='organisation_images/')),
                ('organisationImage2', models.ImageField(blank=True, null=True, upload_to='organisation_images/')),
                ('organisationImage3', models.ImageField(blank=True, null=True, upload_to='organisation_images/')),
                ('organisationPaymentQR', models.ImageField(blank=True, null=True, upload_to='organisation_payment_qr/')),
                ('acceptQrDonations', models.BooleanField(default=False)),
                ('organisationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(limit_choices_to={'isOrganisation': True}, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_has_organisations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'isOrganisation': False}, on_delete=django.db.models.deletion.CASCADE, related_name='user_has_organisations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
