# Generated by Django 5.0 on 2024-01-05 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypApp', '0004_alter_organisationdetails_organisationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdetails',
            name='organisationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
