# Generated by Django 5.0 on 2024-01-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypApp', '0005_alter_organisationdetails_organisationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rejectionReason',
            field=models.TextField(default=''),
        ),
    ]
