# Generated by Django 5.0 on 2024-02-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypApp', '0006_users_rejectionreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hasBeenUpdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='reviewDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
