# Generated by Django 5.0 on 2024-02-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypApp', '0009_alter_users_rejectionreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationdetails',
            name='organisationPaymentQR',
        ),
    ]
