# Generated by Django 5.0 on 2024-02-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypApp', '0010_remove_organisationdetails_organisationpaymentqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isNewUser',
            field=models.BooleanField(default=False),
        ),
    ]
