# Generated by Django 5.0 on 2024-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypApp', '0011_users_isnewuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationdetails',
            name='paidToDate',
            field=models.IntegerField(default=0),
        ),
    ]
