# Generated by Django 5.0 on 2024-02-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypApp', '0012_organisationdetails_paidtodate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdetails',
            name='paidToDate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
